## Computer Vision Final Project - Six Sigma group
### Anupriya Dhiman
### Pranit Malik
### Sagar S
### Syed Nizamuddin
### Twinkle Chavda
### Vishnu Vardhan


### Importing Libraries

In [1]:
import cv2
import os
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report

C:\Users\SagarSRK\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\SagarSRK\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\SagarSRK\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


### Data Preparation , Converting Color, Resizing, Flattening appending and Converting to Array

In [7]:
data = []
labels = []

for folder_name in os.listdir('C:/Users/SagarSRK/Desktop/DS/'):
    for image_name in os.listdir('C:/Users/SagarSRK/Desktop/DS/' + folder_name):
        image_path = 'C:/Users/SagarSRK/Desktop/DS/' + folder_name + '/' + image_name
        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        image = cv2.resize(image, (128, 128))
        data.append(image.flatten())
        labels.append(folder_name)
        

data = np.array(data, dtype='float') / 255.0

print(data)

[[0.4627451  0.41176471 0.44705882 ... 0.14509804 0.14901961 0.15686275]
 [0.13333333 0.1372549  0.16470588 ... 0.36078431 0.35294118 0.36470588]
 [0.02352941 0.02352941 0.02352941 ... 0.07843137 0.07058824 0.08235294]
 ...
 [0.36862745 0.34901961 0.30588235 ... 0.08627451 0.08235294 0.08235294]
 [0.23921569 0.23529412 0.23137255 ... 0.12156863 0.12941176 0.12941176]
 [0.03529412 0.03137255 0.03137255 ... 0.03529412 0.03921569 0.04705882]]


### Splitting the dataset into training and testing sets

In [126]:
(trainX, testX, trainY, testY) = train_test_split(data, labels, test_size=0.50, random_state=50)

trainX

array([[0.01568627, 0.01960784, 0.01960784, ..., 0.12156863, 0.12941176,
        0.1254902 ],
       [0.07843137, 0.07058824, 0.06666667, ..., 0.49019608, 0.48627451,
        0.4745098 ],
       [0.00784314, 0.00784314, 0.00784314, ..., 0.18823529, 0.20392157,
        0.21176471],
       ...,
       [0.02745098, 0.02352941, 0.02352941, ..., 0.49411765, 0.50196078,
        0.50588235],
       [0.08627451, 0.08627451, 0.08235294, ..., 0.10980392, 0.11764706,
        0.10980392],
       [0.49411765, 0.49803922, 0.51372549, ..., 0.05490196, 0.04313725,
        0.03529412]])

### Model selection and training with Multiple Models

### Logistic Regression

In [127]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(trainX,trainY)
y_pred = model.predict(testX)
print(classification_report(testY, y_pred))

              precision    recall  f1-score   support

    Chickpea       0.50      0.49      0.49        41
        Rice       0.21      0.27      0.24        22
     Toordal       0.47      0.35      0.40        23

    accuracy                           0.40        86
   macro avg       0.39      0.37      0.38        86
weighted avg       0.42      0.40      0.40        86



In [139]:
image = cv2.imread('C:/Users/SagarSRK/Desktop/DS/Toordal/ToorDal (28).JPEG')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image = cv2.resize(image, (128, 128))
image = image.flatten() / 255.0
prediction = model.predict_proba([image])
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(labels)
predicted_class = np.argmax(prediction, axis=1)
predicted_class_name = le.inverse_transform(predicted_class)
print("Predicted class: ", predicted_class_name[0])

Predicted class:  Toordal


### Random forest

In [129]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(trainX, trainY)
y_pred = model.predict(testX)
y_pred = model.predict(testX)
print(classification_report(testY, y_pred))

              precision    recall  f1-score   support

    Chickpea       0.58      0.78      0.67        41
        Rice       0.44      0.32      0.37        22
     Toordal       0.53      0.35      0.42        23

    accuracy                           0.55        86
   macro avg       0.52      0.48      0.49        86
weighted avg       0.53      0.55      0.52        86



In [135]:
image = cv2.imread('C:/Users/SagarSRK/Desktop/DS/Toordal/ToorDal (28).JPEG')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image = cv2.resize(image, (128, 128))
image = image.flatten() / 255.0
prediction = model.predict_proba([image])
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(labels)
predicted_class = np.argmax(prediction, axis=1)
predicted_class_name = le.inverse_transform(predicted_class)
print("Predicted class: ", predicted_class_name[0])

Predicted class:  Toordal


### Naive Bayes

In [131]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(trainX, trainY)
y_pred = model.predict(testX)
y_pred = model.predict(testX)
print(classification_report(testY, y_pred))

              precision    recall  f1-score   support

    Chickpea       0.64      0.61      0.62        41
        Rice       0.12      0.09      0.11        22
     Toordal       0.45      0.61      0.52        23

    accuracy                           0.48        86
   macro avg       0.41      0.44      0.42        86
weighted avg       0.46      0.48      0.46        86



In [136]:
image = cv2.imread('C:/Users/SagarSRK/Desktop/DS/Rice/Rice (14).JPEG')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image = cv2.resize(image, (128, 128))
image = image.flatten() / 255.0
prediction = model.predict_proba([image])
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(labels)
predicted_class = np.argmax(prediction, axis=1)
predicted_class_name = le.inverse_transform(predicted_class)
print("Predicted class: ", predicted_class_name[0])

Predicted class:  Rice


### KNN

In [133]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(trainX, trainY)
y_pred = model.predict(testX)
y_pred = model.predict(testX)
print(classification_report(testY, y_pred))

              precision    recall  f1-score   support

    Chickpea       0.55      0.59      0.56        41
        Rice       0.17      0.18      0.18        22
     Toordal       0.53      0.43      0.48        23

    accuracy                           0.44        86
   macro avg       0.42      0.40      0.41        86
weighted avg       0.45      0.44      0.44        86



C:\Users\SagarSRK\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\SagarSRK\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `k

In [134]:
image = cv2.imread('C:/Users/SagarSRK/Desktop/DS/Chickpea/Chickpea (9).jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image = cv2.resize(image, (128, 128))
image = image.flatten() / 255.0
prediction = model.predict_proba([image])
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(labels)
predicted_class = np.argmax(prediction, axis=1)
predicted_class_name = le.inverse_transform(predicted_class)
print("Predicted class: ", predicted_class_name[0])

Predicted class:  Chickpea
